# roles/app_native/handlers/main.yml
---
- name: restart barq
  systemd:
    name: "{{ service_name }}"
    state: restarted
    daemon_reload: yes

- name: daemon-reload
  systemd:
    daemon_reload: yes

